draw dot on target location
overextended/qtarget pull request #70
Opened 2022-03-27 16:34 UTC by xtrsyz

2022-03-28 20:00 UTC, BerkieBb commented
Instead of using `_` as the index of `listSprites`, change the `_` in the for loop to something like `k` and use that

2022-03-29 18:45 UTC, BerkieBb commented
Also, don't use GetDistanceBetweenCoords with lua, use lua math
`#(vector3 - vector3)`
In your case
`#(GetEntityCoords(playerPed) - zone.center)`

2022-04-02 21:44 UTC, benzon commented
The only issue i got with this code right now, is you got to be very close before it draws, where it should maybe draw earlyer, so you dont have to be right up in the face of the "interest poiunt"

2022-04-02 22:27 UTC, xtrsyz commented
then add Config.DrawDistance

2022-04-03 18:32 UTC, BerkieBb requested changes

2022-04-03 18:32 UTC, BerkieBb commented on client.lua
> +									Wait(1)
You shouldn't wait 1 millisecond here, this could cause flickering for people with higher frames, change it to 0

2022-04-03 18:32 UTC, BerkieBb commented on client.lua
> +									DrawSprite("shared", "emptydot_32", 0, 0, 0.02, 0.035, 0, 255,255,255, 255.0)
I don't know if it is needed, but everywhere that I see `SetDrawOrigin` being used, [`ClearDrawOrigin`](https://docs.fivem.net/natives/?_0xFF0B610F6BE0D7AF) is used after that in the same loop, probably to clear the draworigin after it's done setting it so it can set again and doesn't have to replace data I guess

2022-04-03 18:33 UTC, BerkieBb commented on client.lua
> +						if #(pedcoords - zone.center) < Config.DrawDistance and not listSprite[k] then
```suggestion
						if #(pedcoords - zone.center) < (zone.targetoptions.drawDistance or Config.DrawDistance) and not listSprite[k] then
```
You could change this to allow individual draw distance per zone

2022-04-05 14:31 UTC, BerkieBb commented
One issue I've noticed when testing this is, when you keep the eye open and walk away from the option whenever the sprite is showing, the sprite won't go away and will just stay there no matter how far away you're but only when the eye is kept open

2022-04-05 14:44 UTC, BerkieBb requested changes

2022-04-05 14:44 UTC, BerkieBb commented on client.lua
> +				if Config.DrawSprite then pedcoords = GetEntityCoords(PlayerPedId()) end
You can use `playerPed` here instead of `PlayerPedId()`

2022-04-10 10:02 UTC, xtrsyz reviewed
check this

2022-04-10 10:05 UTC, BerkieBb commented
I'm going to check it out later today

2022-04-10 18:16 UTC, BerkieBb commented
It looks good now, but I seem to notice a slight increase in the usage, for me that is 0.01ms increase with each circle drawn, so if there are a few near me, it could increase to 0.10ms or even higher on people with worse systems maybe

2022-04-10 19:43 UTC, thelindat commented
Not really sure of the purpose for this feature but there’s no need to create a new thread for every single DrawSprite.

2022-04-11 06:35 UTC, BerkieBb commented on client.lua
> +			Wait(0)
The `wait` variable isn't used with the Wait here

2022-04-11 17:09 UTC, BerkieBb commented on client.lua
> +			for k, zone in pairs(listSprite) do
Last thing, `k` is unused here, you can change that to an underscore just to not make it show as an unused variable

2022-04-12 05:44 UTC, xtrsyz commented on client.lua
> +			for k, zone in pairs(listSprite) do
done

2022-04-16 11:28 UTC, BerkieBb approved these changes

2022-04-16 11:34 UTC, merged